package com.vaadin.tests.components.ui;

import com.vaadin.server.VaadinRequest;
import com.vaadin.tests.components.AbstractReindeerTestUI;

/**
 * Empty test ui to check auto-generated style name for UI.
 *
 * @author Vaadin Ltd
 */
public class UIAutoGeneratedStyleName extends AbstractReindeerTestUI {

    @Override
    protected void setup(VaadinRequest request) {
    }

    @Override
    protected String getTestDescription() {
        return "Add UI specific autogenerated style name to ui div element"
                + " and overlays container";
    }

    @Override
    protected Integer getTicketNumber() {
        return 14670;
    }

}
