daysUntilStale: 10335
daysUntilClose: 30
exemptLabels:
 - BFP
 - Pinned
staleLabel: Stale
only: issues
markComment: |
  A lot of tickets have been left hanging in the issue tracker through the years. Some of them are still relevant, some of them have been fixed through some other ticket a long time ago, and some are no longer valid.

  To get a better overview of what is important and still relevant, we are closing old tickets which have not been touched in a long time. No further work will be done on this ticket unless someone indicates that it's still relevant.

  You can write a comment here to prevent the ticket from getting closed if you have verified that it's still an issue with the latest Framework version. If the ticket has already been closed, you can of course also create a new ticket with any updated information.
