package com.vaadin.tests.components.ui;

import com.vaadin.tests.tb3.MultiBrowserTest;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.util.Locale;

/**
 * Test to check auto-generated style name for UI div and overlays div.
 *
 * @author Vaadin Ltd
 */
public class UIAutoGeneratedStyleNameTest extends MultiBrowserTest {

    @Test
    public void testUiStyleName() {
        openTestURL();

        Assert.assertTrue(
                "UI div element doesn't contain autogenerated style name",
                containsStyle(getDriver().findElement(By.className("v-app")),
                        UIAutoGeneratedStyleName.class.getSimpleName()
                                .toLowerCase(Locale.ENGLISH)));

        Assert.assertTrue(
                "Overlays div element doesn't contain autogenerated style name",
                containsStyle(
                        getDriver().findElement(
                                By.className("v-overlay-container")),
                        UIAutoGeneratedStyleName.class.getSimpleName()
                                .toLowerCase(Locale.ENGLISH)));
    }

    private boolean containsStyle(WebElement element, String style) {
        return element.getAttribute("class").contains(style);
    }
}
