language: java
jdk: oraclejdk8
sudo: false

dist: trusty
sudo: required

cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all vaadin artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/*
