---
title: Using Vaadin with Kotlin
order: 1100
layout: page
---

[[getting-started.kotlin]]
= Using Vaadin with Kotlin

You can use Vaadin with any the Kotlin language as well. Kotlin offers
awesome tooling which includes a plugin for Intellij IDEA, Eclipse and Netbeans.
The Kotlin plugin allows you to convert any Java class to Kotlin, so the easiest way
is to generate the sample link:https://vaadin.com/maven[Java Vaadin Maven project] and
then convert the [filename]#MyUI# class to Kotlin, by pressing
kbd:[Ctrl+Alt+Shift+K].

The link:https://github.com/mvysny/karibu-dsl[Karibu-DSL] library offers a more Kotlin-like
API for Vaadin. The library will allow you to create
your UI in a hierarchical way. For more details please see
link:https://kotlinlang.org/docs/reference/type-safe-builders.html[Kotlin Type-Safe Builders].
There is a link:https://github.com/mvysny/karibu-helloworld-application[Karibu Helloworld Application]
sample which demonstrates this technique. It's a standard Gradle project, so you
just need to git clone the project and open it in your IDE. The hierarchical code looks as follows:

[source, kotlin]
----
@Theme("mytheme")
class MyUI : UI() {

    private lateinit var layout: VerticalLayout

    @Override
    override fun init(vaadinRequest: VaadinRequest) {
        layout = verticalLayout {
            val name = textField {
                caption = "Type your name here:"
            }
            button("Click Me", {
                println("Thanks ${name.value}, it works!")
                layout.label("Thanks ${name.value}, it works!")
            })
        }
    }
}
----

If you need to include a database support to your application, you can also include the
link:http://www.vaadinonkotlin.eu/[Vaadin-on-Kotlin] library to your application. Just follow
the Getting Started tutorial there, to set up everything.
