/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.vaadin.sass.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int INTERPOLATION = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int CDO = 13;
  /** RegularExpression Id. */
  int CDC = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int DASHMATCH = 17;
  /** RegularExpression Id. */
  int INCLUDES = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int PRECEDES = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int LBRACKET = 26;
  /** RegularExpression Id. */
  int RBRACKET = 27;
  /** RegularExpression Id. */
  int ANY = 28;
  /** RegularExpression Id. */
  int PARENT = 29;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int LPARAN = 31;
  /** RegularExpression Id. */
  int RPARAN = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int NONASCII = 34;
  /** RegularExpression Id. */
  int H = 35;
  /** RegularExpression Id. */
  int UNICODE = 36;
  /** RegularExpression Id. */
  int ESCAPE = 37;
  /** RegularExpression Id. */
  int NMSTART = 38;
  /** RegularExpression Id. */
  int NMCHAR = 39;
  /** RegularExpression Id. */
  int STRINGCHAR = 40;
  /** RegularExpression Id. */
  int D = 41;
  /** RegularExpression Id. */
  int NAME = 42;
  /** RegularExpression Id. */
  int TO = 43;
  /** RegularExpression Id. */
  int THROUGH = 44;
  /** RegularExpression Id. */
  int EACH_IN = 45;
  /** RegularExpression Id. */
  int MIXIN_SYM = 46;
  /** RegularExpression Id. */
  int INCLUDE_SYM = 47;
  /** RegularExpression Id. */
  int FUNCTION_SYM = 48;
  /** RegularExpression Id. */
  int RETURN_SYM = 49;
  /** RegularExpression Id. */
  int DEBUG_SYM = 50;
  /** RegularExpression Id. */
  int WARN_SYM = 51;
  /** RegularExpression Id. */
  int FOR_SYM = 52;
  /** RegularExpression Id. */
  int EACH_SYM = 53;
  /** RegularExpression Id. */
  int WHILE_SYM = 54;
  /** RegularExpression Id. */
  int IF_SYM = 55;
  /** RegularExpression Id. */
  int ELSE_SYM = 56;
  /** RegularExpression Id. */
  int EXTEND_SYM = 57;
  /** RegularExpression Id. */
  int MOZ_DOCUMENT_SYM = 58;
  /** RegularExpression Id. */
  int SUPPORTS_SYM = 59;
  /** RegularExpression Id. */
  int GUARDED_SYM = 60;
  /** RegularExpression Id. */
  int STRING = 61;
  /** RegularExpression Id. */
  int IDENT = 62;
  /** RegularExpression Id. */
  int NUMBER = 63;
  /** RegularExpression Id. */
  int _URL = 64;
  /** RegularExpression Id. */
  int URL = 65;
  /** RegularExpression Id. */
  int VARIABLE = 66;
  /** RegularExpression Id. */
  int PERCENTAGE = 67;
  /** RegularExpression Id. */
  int PT = 68;
  /** RegularExpression Id. */
  int MM = 69;
  /** RegularExpression Id. */
  int CM = 70;
  /** RegularExpression Id. */
  int PC = 71;
  /** RegularExpression Id. */
  int IN = 72;
  /** RegularExpression Id. */
  int PX = 73;
  /** RegularExpression Id. */
  int EMS = 74;
  /** RegularExpression Id. */
  int EXS = 75;
  /** RegularExpression Id. */
  int DEG = 76;
  /** RegularExpression Id. */
  int RAD = 77;
  /** RegularExpression Id. */
  int GRAD = 78;
  /** RegularExpression Id. */
  int MS = 79;
  /** RegularExpression Id. */
  int SECOND = 80;
  /** RegularExpression Id. */
  int HZ = 81;
  /** RegularExpression Id. */
  int KHZ = 82;
  /** RegularExpression Id. */
  int DIMEN = 83;
  /** RegularExpression Id. */
  int HASH = 84;
  /** RegularExpression Id. */
  int IMPORT_SYM = 85;
  /** RegularExpression Id. */
  int MEDIA_SYM = 86;
  /** RegularExpression Id. */
  int CHARSET_SYM = 87;
  /** RegularExpression Id. */
  int PAGE_SYM = 88;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 89;
  /** RegularExpression Id. */
  int ATKEYWORD = 90;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 91;
  /** RegularExpression Id. */
  int RANGE0 = 92;
  /** RegularExpression Id. */
  int RANGE1 = 93;
  /** RegularExpression Id. */
  int RANGE2 = 94;
  /** RegularExpression Id. */
  int RANGE3 = 95;
  /** RegularExpression Id. */
  int RANGE4 = 96;
  /** RegularExpression Id. */
  int RANGE5 = 97;
  /** RegularExpression Id. */
  int RANGE6 = 98;
  /** RegularExpression Id. */
  int RANGE = 99;
  /** RegularExpression Id. */
  int UNI = 100;
  /** RegularExpression Id. */
  int UNICODERANGE = 101;
  /** RegularExpression Id. */
  int FUNCTION = 102;
  /** RegularExpression Id. */
  int UNKNOWN = 103;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_INTERPOLATION = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"#{\"",
    "<token of kind 3>",
    "\"}\"",
    "\"//\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"<!--\"",
    "\"-->\"",
    "\"{\"",
    "\"}\"",
    "\"|=\"",
    "\"~=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"&\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "\"to\"",
    "\"through\"",
    "\"in\"",
    "\"@mixin\"",
    "\"@include\"",
    "\"@function\"",
    "\"@return\"",
    "\"@debug\"",
    "\"@warn\"",
    "\"@for\"",
    "\"@each\"",
    "\"@while\"",
    "\"@if\"",
    "\"@else\"",
    "\"@extend\"",
    "\"@-moz-document\"",
    "\"@supports\"",
    "<GUARDED_SYM>",
    "<STRING>",
    "<IDENT>",
    "<NUMBER>",
    "<_URL>",
    "<URL>",
    "<VARIABLE>",
    "<PERCENTAGE>",
    "<PT>",
    "<MM>",
    "<CM>",
    "<PC>",
    "<IN>",
    "<PX>",
    "<EMS>",
    "<EXS>",
    "<DEG>",
    "<RAD>",
    "<GRAD>",
    "<MS>",
    "<SECOND>",
    "<HZ>",
    "<KHZ>",
    "<DIMEN>",
    "<HASH>",
    "\"@import\"",
    "\"@media\"",
    "\"@charset\"",
    "\"@page\"",
    "\"@font-face\"",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<FUNCTION>",
    "<UNKNOWN>",
  };

}
