/*
@VaadinApache2LicenseForJavaFiles@
 */
package com.vaadin.annotations;

/**
 * Marker annotation for automatically generated code elements.
 * 
 * These elements may be modified or removed by code generation.
 * 
 * @author Vaadin Ltd.
 * @version
 * @VERSION@
 * @since 6.0
 */
public @interface AutoGenerated {

}
