/*
@ITMillApache2LicenseForJavaFiles@
 */
package com.vaadin.terminal.gwt.client.ui.dd;

import com.vaadin.terminal.gwt.widgetsetutils.AcceptCriteriaFactoryGenerator;

/**
 * Generated by {@link AcceptCriteriaFactoryGenerator}
 * 
 */
public abstract class VAcceptCriterionFactory {

    public abstract VAcceptCriterion get(String name);
}
