/*
@VaadinApache2LicenseForJavaFiles@
 */
package com.vaadin.shared;

public class ApplicationConstants {
    // This indicates the whole page is generated by us (not embedded)
    public static final String GENERATED_BODY_CLASSNAME = "v-generated-body";

    public static final String APP_REQUEST_PATH = "APP/";

    public static final String UIDL_REQUEST_PATH = "UIDL/";

    public static final String CONNECTOR_RESOURCE_PREFIX = APP_REQUEST_PATH
            + "CONNECTOR";

    public static final String APP_PROTOCOL_PREFIX = "app://";
    public static final String CONNECTOR_PROTOCOL_PREFIX = "connector://";
    public static final String UIDL_SECURITY_TOKEN_ID = "Vaadin-Security-Key";
    /**
     * Name of the parameter used to transmit root ids back and forth
     */
    public static final String ROOT_ID_PARAMETER = "rootId";

    public static final String PARAM_UNLOADBURST = "onunloadburst";

    @Deprecated
    public static final String UPDATE_VARIABLE_INTERFACE = "v";
    @Deprecated
    public static final String UPDATE_VARIABLE_METHOD = "v";

    public static final String PORTLET_RESOUCE_URL_BASE = "portletAppURLBase";

    public static final String V_RESOURCE_PATH = "v-resourcePath";

    @Deprecated
    public static final String DRAG_AND_DROP_CONNECTOR_ID = "DD";
}
