/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.vaadin.sass.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int CDO = 10;
  /** RegularExpression Id. */
  int CDC = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int DASHMATCH = 14;
  /** RegularExpression Id. */
  int CARETMATCH = 15;
  /** RegularExpression Id. */
  int DOLLARMATCH = 16;
  /** RegularExpression Id. */
  int STARMATCH = 17;
  /** RegularExpression Id. */
  int INCLUDES = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int PRECEDES = 24;
  /** RegularExpression Id. */
  int SUCCEEDS = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int LBRACKET = 27;
  /** RegularExpression Id. */
  int RBRACKET = 28;
  /** RegularExpression Id. */
  int ANY = 29;
  /** RegularExpression Id. */
  int PARENT = 30;
  /** RegularExpression Id. */
  int DOT = 31;
  /** RegularExpression Id. */
  int LPARAN = 32;
  /** RegularExpression Id. */
  int RPARAN = 33;
  /** RegularExpression Id. */
  int COMPARE = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int NOT_EQ = 37;
  /** RegularExpression Id. */
  int COLON = 38;
  /** RegularExpression Id. */
  int INTERPOLATION = 39;
  /** RegularExpression Id. */
  int NONASCII = 40;
  /** RegularExpression Id. */
  int H = 41;
  /** RegularExpression Id. */
  int UNICODE = 42;
  /** RegularExpression Id. */
  int ESCAPE = 43;
  /** RegularExpression Id. */
  int NMSTART = 44;
  /** RegularExpression Id. */
  int NMCHAR = 45;
  /** RegularExpression Id. */
  int STRINGCHAR = 46;
  /** RegularExpression Id. */
  int D = 47;
  /** RegularExpression Id. */
  int NAME = 48;
  /** RegularExpression Id. */
  int TO = 49;
  /** RegularExpression Id. */
  int THROUGH = 50;
  /** RegularExpression Id. */
  int EACH_IN = 51;
  /** RegularExpression Id. */
  int MIXIN_SYM = 52;
  /** RegularExpression Id. */
  int INCLUDE_SYM = 53;
  /** RegularExpression Id. */
  int FUNCTION_SYM = 54;
  /** RegularExpression Id. */
  int RETURN_SYM = 55;
  /** RegularExpression Id. */
  int DEBUG_SYM = 56;
  /** RegularExpression Id. */
  int WARN_SYM = 57;
  /** RegularExpression Id. */
  int FOR_SYM = 58;
  /** RegularExpression Id. */
  int EACH_SYM = 59;
  /** RegularExpression Id. */
  int WHILE_SYM = 60;
  /** RegularExpression Id. */
  int IF_SYM = 61;
  /** RegularExpression Id. */
  int ELSE_SYM = 62;
  /** RegularExpression Id. */
  int EXTEND_SYM = 63;
  /** RegularExpression Id. */
  int MOZ_DOCUMENT_SYM = 64;
  /** RegularExpression Id. */
  int SUPPORTS_SYM = 65;
  /** RegularExpression Id. */
  int MICROSOFT_RULE = 66;
  /** RegularExpression Id. */
  int IF = 67;
  /** RegularExpression Id. */
  int GUARDED_SYM = 68;
  /** RegularExpression Id. */
  int STRING = 69;
  /** RegularExpression Id. */
  int IDENT = 70;
  /** RegularExpression Id. */
  int NUMBER = 71;
  /** RegularExpression Id. */
  int _URL = 72;
  /** RegularExpression Id. */
  int URL = 73;
  /** RegularExpression Id. */
  int VARIABLE = 74;
  /** RegularExpression Id. */
  int PERCENTAGE = 75;
  /** RegularExpression Id. */
  int PT = 76;
  /** RegularExpression Id. */
  int MM = 77;
  /** RegularExpression Id. */
  int CM = 78;
  /** RegularExpression Id. */
  int PC = 79;
  /** RegularExpression Id. */
  int IN = 80;
  /** RegularExpression Id. */
  int PX = 81;
  /** RegularExpression Id. */
  int EMS = 82;
  /** RegularExpression Id. */
  int EXS = 83;
  /** RegularExpression Id. */
  int DEG = 84;
  /** RegularExpression Id. */
  int RAD = 85;
  /** RegularExpression Id. */
  int GRAD = 86;
  /** RegularExpression Id. */
  int MS = 87;
  /** RegularExpression Id. */
  int SECOND = 88;
  /** RegularExpression Id. */
  int HZ = 89;
  /** RegularExpression Id. */
  int KHZ = 90;
  /** RegularExpression Id. */
  int DIMEN = 91;
  /** RegularExpression Id. */
  int HASH = 92;
  /** RegularExpression Id. */
  int IMPORT_SYM = 93;
  /** RegularExpression Id. */
  int MEDIA_SYM = 94;
  /** RegularExpression Id. */
  int CHARSET_SYM = 95;
  /** RegularExpression Id. */
  int PAGE_SYM = 96;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 97;
  /** RegularExpression Id. */
  int ATKEYWORD = 98;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 99;
  /** RegularExpression Id. */
  int RANGE0 = 100;
  /** RegularExpression Id. */
  int RANGE1 = 101;
  /** RegularExpression Id. */
  int RANGE2 = 102;
  /** RegularExpression Id. */
  int RANGE3 = 103;
  /** RegularExpression Id. */
  int RANGE4 = 104;
  /** RegularExpression Id. */
  int RANGE5 = 105;
  /** RegularExpression Id. */
  int RANGE6 = 106;
  /** RegularExpression Id. */
  int RANGE = 107;
  /** RegularExpression Id. */
  int UNI = 108;
  /** RegularExpression Id. */
  int UNICODERANGE = 109;
  /** RegularExpression Id. */
  int REMOVE = 110;
  /** RegularExpression Id. */
  int APPEND = 111;
  /** RegularExpression Id. */
  int CONTAINS = 112;
  /** RegularExpression Id. */
  int FUNCTION = 113;
  /** RegularExpression Id. */
  int UNKNOWN = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"//\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"<!--\"",
    "\"-->\"",
    "\"{\"",
    "\"}\"",
    "\"|=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"~=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"<\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"&\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"||\"",
    "\"&&\"",
    "\"!=\"",
    "\":\"",
    "<INTERPOLATION>",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "\"to\"",
    "\"through\"",
    "\"in\"",
    "\"@mixin\"",
    "\"@include\"",
    "\"@function\"",
    "\"@return\"",
    "\"@debug\"",
    "\"@warn\"",
    "\"@for\"",
    "\"@each\"",
    "\"@while\"",
    "\"@if\"",
    "\"@else\"",
    "\"@extend\"",
    "\"@-moz-document\"",
    "\"@supports\"",
    "<MICROSOFT_RULE>",
    "\"if\"",
    "<GUARDED_SYM>",
    "<STRING>",
    "<IDENT>",
    "<NUMBER>",
    "<_URL>",
    "<URL>",
    "<VARIABLE>",
    "<PERCENTAGE>",
    "<PT>",
    "<MM>",
    "<CM>",
    "<PC>",
    "<IN>",
    "<PX>",
    "<EMS>",
    "<EXS>",
    "<DEG>",
    "<RAD>",
    "<GRAD>",
    "<MS>",
    "<SECOND>",
    "<HZ>",
    "<KHZ>",
    "<DIMEN>",
    "<HASH>",
    "\"@import\"",
    "\"@media\"",
    "\"@charset\"",
    "\"@page\"",
    "\"@font-face\"",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<REMOVE>",
    "<APPEND>",
    "<CONTAINS>",
    "<FUNCTION>",
    "<UNKNOWN>",
  };

}
