package com.itmill.toolkit.annotations;

/**
 * Marker annotation for automatically generated code elements.
 * 
 * These elements may be modified or removed by code generation.
 * 
 * @author IT Mill Ltd.
 * @version
 * @VERSION@
 * @since 6.0
 */
public @interface AutoGenerated {

}
