package com.vaadin.terminal.gwt.client;

import com.google.gwt.core.client.GWT;
import com.google.gwt.json.client.JSONArray;
import com.google.gwt.json.client.JSONObject;
import com.vaadin.terminal.gwt.client.communication.JsonDecoder;
import com.vaadin.terminal.gwt.client.communication.VaadinSerializer;

//TODO This should be autogenerated
public class ComponentState_Serializer implements VaadinSerializer {

    public ComponentState deserialize(JSONObject jsonValue,
            VPaintableMap idMapper) {
        ComponentState state = GWT.create(ComponentState.class);

        // For (Field f : fields) {
        // state.setState((Map<String, Object>)
        // JsonDecoder.convertMap(jsonValue,
        // idMapper));
        JSONArray jsonHeight = (JSONArray) jsonValue.get("height");
        state.setHeight((String) JsonDecoder.convertValue(jsonHeight, idMapper));

        JSONArray jsonWidth = (JSONArray) jsonValue.get("width");
        state.setWidth((String) JsonDecoder.convertValue(jsonWidth, idMapper));

        return state;
    }
}
