---
title: Downloading Add-ons from Vaadin Directory
order: 2
layout: page
---

[[addons.downloading]]
= Downloading Add-ons from Vaadin Directory

If you are not using Maven or a Maven-compatible dependency manager such as Ivy,
or want to manage for your libraries manually, you can download add-on packages
from the details page of an add-on in Vaadin Directory.

. Select the version; some add-ons have several versions available. The latest is
shown by default, but you can choose another the version to download from the
dropdown menu in the header of the details page.

. Click [guibutton]#Download Now# and save the JAR or Zip file on your computer.

. If the add-on is packaged in a Zip package, unzip the package and follow any
instructions provided inside the package. Typically, you just need to copy a JAR
file to your web project under the [filename]#WEB-INF/lib# directory.

+
Note that some add-ons may require other libraries. You can resolve such
dependencies manually, but we recommend using a dependency manager such as Ivy
or Maven in your project.

. Update and recompile your project. In Eclipse, select the project and press F5.

. You may need to compile the client-side implementations of the add-on
components, that is, a __widget set__. This is the case for majority of add-ons,
except for pure server-side, theme, or data binding add-ons. Compiling the
widget set depends on the build environment. See <<addons.downloading.ant>>, or
later in this chapter for instructions for compiling the widget set with Eclipse
and
Maven.+
////
See &lt;xref linkend="addons.compiling"/&gt; for
instructions.
////

. Update the project in your development web server and possibly restart the
server.


[[addons.downloading.ant]]
== Compiling Widget Sets with an Ant Script

If you need to compile the widget set with an Ant script, you can find a script
template package at the link:http://vaadin.com/download/[Vaadin download page].
You can copy the files in the package to your project and, once configured, use
it by running Ant in the directory.

If you are using an IDE such as Eclipse, __always__ remember to refresh the
project to synchronize it with the filesystem after compiling the widget set
outside the IDE.




