---
title: Overview
order: 1
layout: page
---

[[addons.overview]]
= Overview

In addition to the components, layouts, themes, and data sources built in into
the core Vaadin library, many others are available as add-ons.
link:http://vaadin.com/directory/[Vaadin Directory] provides a rich collection
of add-ons for Vaadin, and you may find others from independent sources. Add-ons
are also one way to share your own components between projects.

Installation of add-ons from Vaadin Directory is simple, just adding an Ivy or
Maven dependency, or downloading the JAR package and and dropping it in the web
library folder of the project. Most add-ons include a widget set, which you need
to compile, but it's usually just a click of a button or a single command.

After trying out an add-on, you can give some feedback to the author of the
add-on by rating the add-on with one to five stars and optionally leaving a
comment. Most add-ons also have a discussion forum thread for user feedback and
questions.

Add-ons available from Vaadin Directory are distributed under different
licenses, of which some are commercial. While the add-ons can be downloaded
directly, you should note their license and other terms and conditions. Many are
offered under a dual licensing agreement so that they can be used in open source
projects for free, and many have a trial period for closed-source development.
Commercial Vaadin add-ons distributed under the CVAL license require installing
a license key as instructed in
<<dummy/../../../framework/addons/addons-cval#addons.cval,"Installing Commercial
Vaadin Add-on Licence">>.



