/* 
@ITMillApache2LicenseForJavaFiles@
 */

package com.itmill.toolkit.terminal;

import java.io.IOException;

/**
 * <code>PaintExcepection</code> is thrown if painting of a component fails.
 * 
 * @author IT Mill Ltd.
 * @version
 * @VERSION@
 * @since 3.0
 */
public class PaintException extends IOException {

    /**
     * Serial generated by eclipse.
     */
    private static final long serialVersionUID = 3762535607221891897L;

    /**
     * Constructs an instance of <code>PaintExeception</code> with the
     * specified detail message.
     * 
     * @param msg
     *                the detail message.
     */
    public PaintException(String msg) {
        super(msg);
    }

    /**
     * Constructs an instance of <code>PaintExeception</code> from
     * IOException.
     * 
     * @param exception
     *                the original exception.
     */
    public PaintException(IOException exception) {
        super(exception.getMessage());
    }
}
